### ISSUE TITLE
does the snowshell gui offer the option to choose between photo and artwork?

### ISSUE THREAD

**Issue by Ahmed-Mokhles** [YukihoAA/waifu2x_snowshell#16]
the original waifu2x website has a setting that changes the mode between "photo" and "artwork", im guessing each is optimised for the respective type of image.
however, snowshell does not seem to have this setting, unless i missed it.
so does it exist in snowshell? and if not, is there a way to enable it by editing some config files or using the CLI instead?

thanks in advance.
![image](https://user-images.githubusercontent.com/34982931/79052161-39099500-7c3d-11ea-9a6b-8148cc80240e.png)

**Comment by YukihoAA** [comment]
If you want to use photo model instead of rgb model, you can select model folder by editing config.ini, if you need other models that does not included in released archive, such as photo model, you should download model folder from converter website which you going to use.

since model folder selection is only add commend "--model-path=xxxx" so if you also need to change processor selection to use other model such as cunnet, you can set customstring in config.ini (CLI commend mode). check the commend from converter website to use it.
