### ISSUE TITLE
Enable Native 4x Upscaling

### ISSUE THREAD

**Issue by ColonelGerdauf** [YukihoAA/waifu2x_snowshell#25]
I see the option in a number of implementations of Waifu2x, including Caffee and Metal. It would be nice to include 4x as a native upscale without needing to enter a custom value.

**Comment by YukihoAA** [comment]
Hi @ColonelGerdauf,

if you enter x4 in custom scale, it will saved after you close program unless you change value again.

also, if you set custom scale like 2.3 or x4 or something, it works as native value that you enter x4 in converter it self.

Instead of add x4 menu as native, I will consider add toggle dialog feature about custom scale to make custom value menu works like native scale button.



The reason why waifu2x_snowshell only includes x1~x2 for menu is if menu has too many items, it does not looks simple..

Second, waifu2x is actually only works at x2 value, but most of converter implements bigger value by internal loop to do x2 for several time. For example, if you run waifu2x as x4, converter actually run x2 twice to make x4, if you run x5, converter actually runs x2 for 3times to make image x16, and resize image to make image x5.

**Comment by YukihoAA** [comment]
I figured out adding toggle menu will cause undermine of consistency. 
Instead, I moved custom scale dialog to mouse position to click save button easier.

It will be much easier to select custom scale menu than before. 

This feature is available from Snowshell v2.3
