### ISSUE TITLE
Proper handling of directly opening images in Snowshell (such as via right-click -> "Open with...")

### ISSUE THREAD

**Issue by NintendoManiac64** [YukihoAA/waifu2x_snowshell#4]
Snowshell doesn't know how to really work at all if you try to right-click an image file and then selecting Snowshell from "Open with..."

Initially it'll want to create a config.ini file, and then when trying to convert it'll fail saying to "check your Windows version".

As a reference, waifu2x-cpp GUI from v5.2 of that program works perfectly via the process of right-clicking an image and selecting waifu2x-cpp GUI from "Open with...".

**Comment by YukihoAA** [comment]
This project is not developed base on waifu2x-converter-cpp
and
I did not designed snowshell works as waifu2x-converter-cpp-gui.

Snowshell is designed for drag and drop conversion. (Not for batch processing) 

This program should not used by Open with. Because working directory should be set to exe path but if you use Open with... than working directory will be set to the directory that photo files in. If that case Snowshell cannot detect waifu2x-converter-cpp and it will shows "check windows version".

If you want simple-right-click-conversion, please use waifu2x-converter-cpp-gui's send To... script instead.

**Comment by YukihoAA** [comment]
Now snowshell supports this function.

try https://github.com/YukihoAA/waifu2x_snowshell/releases/tag/v1.9
